### ISSUE TITLE
Rust on Android

### ISSUE THREAD

**Issue by mcmikecreations** [godot-rust/gdext#1303]
I was trying to figure out how to use gdext on android. Eventually, I found #1250, tried grabbing the attached zip and compile it. It uses `godot = "0.3.4"`. Everything worked and I got the same error as the author of the issue. When I updated the library to `godot = "0.3.5"`, I started getting errors on ADB:
```
09-08 16:35:32.983 23600 23639 E godot   : ERROR: Cannot get class 'Demo'.
09-08 16:35:32.983 23600 23639 E godot   : WARNING: Node Demo of type Demo cannot be created. A placeholder will be created instead.
```
No other configuration changed, same godot 4.4.1 and NDK and so on. I tried creating a new project and a new GDExtension from scratch following the tutorial in your Book, but got the same issue that the node cannot be created. Also, the prints inside `on_level_init` and `on_level_deinit` were not printed (from the [hot-reload example](https://github.com/godot-rust/demo-projects/blob/master/hot-reload/rust/src/lib.rs)).

There are no other issues in the ADB logcat that would say "The library could not be loaded" or so, so I'm gaving trouble debugging anything. I tried building the "game" for linux too (Ubuntu 24.04), everything works fine there. Just the Android build doesn't work. I also tried putting the *.so files in /assets/ in the APK instead of the default location of /libs/arm64-v8a/ and updated the path inside the `.gdextension` file, didn't help.

Has anyone been able to successfully compile a rust GDExtension for android with the latest version of `godot = "0.3.5"`?

**Comment by ansdor** [comment]
I'm the OP of #1250 and I got the same error when trying to compile the demo I created

but I'm pretty sure that's some random issue with my own code in the demo, not godot-rs itself. my main project, the one that made me discover the issue, compiles and runs perfectly on android with godot-rs 0.3.5

I wrote that code in a hurry just to demonstrate the issue, I could probably fix the demo with a few hours or minutes but honestly I don't think it's worth the time. I got a [much more complex project ](https://ansdor.itch.io/fever)working perfectly now, so I say you shouldn't worry too much about that demo.

EDIT: 

I think I fixed it anyway. on the rust directory, update to 0.3.5 then run ```cargo clean```, ```cargo build``` , then open the project in the engine editor (probably related to the .uid file, something must need to be updated), then run the steps to compile for android. it worked for me.

**Comment by mykolamor** [comment]
I've created an example that recreates the issue.
```
Godot 4.4.1
Rust 1.89.0
Clang 20.1.8
```
Built with the following steps:
```
cd testrust
cargo build --target x86_64-unknown-linux-gnu
cargo build --target x86_64-unknown-linux-gnu --release
ANDROID_NDK_HOME=$HOME/Android/Sdk/ndk/23.2.8568313 cargo ndk -t arm64-v8a build
ANDROID_NDK_HOME=$HOME/Android/Sdk/ndk/23.2.8568313 cargo ndk -t arm64-v8a build --release
```
Then export to Android inside godot or via terminal to generate Mytest.apk and run:
```
$HOME/Android/Sdk/platform-tools/adb install Mytest.apk
$HOME/Android/Sdk/platform-tools/adb logcat | grep -iE "godot|mytest"
```
Getting error:
```
09-10 10:07:53.988 10361 10402 E godot   : ERROR: Cannot get class 'Player'.
09-10 10:07:53.988 10361 10402 E godot   :    at: _instantiate_internal (core/object/class_db.cpp:549)
09-10 10:07:53.989 10361 10402 E godot   : WARNING: Node Player of type Player cannot be created. A placeholder will be created instead.
09-10 10:07:53.989 10361 10402 E godot   :    at: instantiate (scene/resources/packed_scene.cpp:276)
```
I can verify the library was correctly added to the apk into `lib/arm64-v8a` by unzipping it. I tried moving the `*.so` files into the `godot` folder and updating the `testrust.gdextension` file [to avoid](https://godot-rust.github.io/book/intro/hello-world.html#admonition-export-paths) having `res://../` relative path, didn't help. I also tried specifying `*.so` inside "Filters to export non-resource files/folders" in the Android Export menu in Godot to make sure the library ended up in the `assets` folder inside the apk, also didn't help. Is there any other troubleshooting I can do?

Can't attach the archive, so made it [publicly hosted](https://syncandshare.lrz.de/getlink/fi8GLXshTU3zqykTik4DXm/test.zip).

**Comment by Bromeon** [comment]
@mcmikecreations Were you able to solve it?

If not, I'd recommend also asking in the Discord. That said, Android is experimental and we currently lack the development resources to make it a first class citizen like Desktop (and hopefully soon, Wasm). So exchanging with others who use Android might be your best bet right now 🙂

**Comment by mykolamor** [comment]
@Bromeon nope, I'll try reaching out, thanks.

**Comment by heckmarr** [comment]
I'd just like to pipe up and say I'm hitting the same wall. I've tried everything to rename/recompile and change. I tried updating Godot, I tried downgrading the plugin to "0.3.4" and still get the same issue. I've decompiled my .apks to make sure the librust.so is in there, and it is, though it's at /lib/*blah*.so

Could that be it? should it be in the jniLib folder? I tried changing and adding android/build/src/debug/jniLibs/arm64-v8a/ but it still cannot find the class

I'm wondering if it's in the android build template now. I'm using 4.5 built from source, I'll check back in tomorrow with my progress. I'll try rebuilding 4.4 and downgrading the plugin.

I'd just like to say, thank you for the wonderful software! I've had endless fun learning rust along with Godot.

**Comment by heckmarr** [comment]
Nevermind! It turned out I wasn't using the right android triple.

`arm64-v8a` should have been `armeabi-v7a`

Compiled the correct version and my app is working as intended! Woohoo!

**Comment by heckmarr** [comment]
Specifically, I'm building for the Oculus Quest 2 from Fedora Linux, and there were a few tweaks, for example the changes to my Rust code don't show if I build just `armeabi-v7a`, I have to build `arm64-v8a`, `armeabi-v7a` and `cargo build` and then it works. I read somewhere that not having a triple build available will make godot do something silly like use the wrong library, but none of the errors I encountered said anything about incompatible files, just `Could not instantiate class`

There! Hope that helps.

**Comment by heckmarr** [comment]
Well now I'm just stumped. I changed back to `arm64-v8a` as it was only copying the librust.so for that architecture into the `android/build` folder on deploy, and now I can't reproduce my problem! Compiling just `arm64-v8a` without `cargo build` works now, when it didn't last night. Whatever I do it works! Aaaah!

The only thing that caused a crash as far as I can tell was opening three debugging sessions for the Quest 2. Just hitting the deploy to device without exiting the application in headset. Gradle warned of `1 incompatible, 1 busy, 1 stopped daemon` and then locks up my whole system and I have to reboot.

But as far as I can tell, the issue I was having has left. Hooray! If anyone can reproduce the `cannot instantiate class` problem I'd love to know what caused me such grief!

**Comment by heckmarr** [comment]
YES! Nailed it down! At some point last night I decided to use `gdext` as a `git` dependency and added a few features. Cut through them one by one and my problem instantly came back when I disabled `experimental-threads` cleaned up the other features, added this line to my `Cargo.toml` under `[dependencies]` and we're off to the races! Solved for me. :100:
EDIT: Fixed so as to not include the unneeded git configuration
`godot = { version = "0.3.5", features = ["experimental-threads"] }`

**Comment by mykolamor** [comment]
So, here are the steps I'm trying now.

1. Updated to Godot 4.5. Checked NDK version to be `28.1.13356709` [here](https://github.com/godotengine/godot/blob/876b290332ec6f2e6d173d08162a02aa7e6ca46d/platform/android/detect.py#L71C12-L71C27).
2. Ditched the cargo ndk command in favor of following the tutorial on gdext website line-by-line.
3. `export CLANG_PATH=/home/me/Android/Sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/linux-x86_64/bin/clang`
4. Checked that all target triples are installed using `rustup target list`
5. `export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=/home/me/Android/Sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang`
6. `cargo build --target=aarch64-linux-android` and `--release`
7. Checked in `.gdextension` for `android.release.arm64 =  "res://../testrust/target/aarch64-linux-android/release/libtestrust.so"`, and for `android.debug.arm64`
8. Inside Godot 4.5, open export, install the official template, target Sdk 35 (same as clang above), only export `arm64-v8a` architecture, click `Export Project` to get an apk, checked checkbox `Export With Debug`
9. @Bromeon one thing that I noticed while tinkering (which doesn't apply to this issue) is that godot falls back to an older Sdk build tools version if the target one is not installed, but since we manually specify the clang version, that would be the wrong one. Is it possible to update the documentation to force users to double-check the warning: `Could not find version of build tools that matches Target SDK, using <older version>`?
10. Now that I have `test.apk`, I can run `adb install test.apk`. I have my emulator on, also can connect my device.
11. See a black screen in the app, check logs, got the usual error:

```
09-22 11:38:12.966 11633 11633 W .example.mytest: Unexpected CPU variant for x86: x86_64.
09-22 11:38:17.896 11633 11660 E godot   : ERROR: Cannot get class 'Player'.
09-22 11:38:17.896 11633 11660 E godot   :    at: _instantiate_internal (core/object/class_db.cpp:546)
09-22 11:38:17.896 11633 11660 E godot   : WARNING: Node Player of type Player cannot be created. A placeholder will be created instead.
09-22 11:38:17.896 11633 11660 E godot   :    at: instantiate (scene/resources/packed_scene.cpp:277)
```

Same errors (except Unexpected CPU variant) on my actual device (Samsung S25U). Now let's try putting the shared lib inside the godot folder, so that the `res://` link doesn't have a `..` in the path.

```
android.debug.arm64 =    "res://libtestrust_android_debug.so"
android.release.arm64 =  "res://libtestrust_android_release.so"
```

Same error. Are there any other steps that I can take to figure this out? Am I doing something wrong according to the steps above? Should I also build for `armeabi-v7a`?

> Note: I'm still using `0.3.5` version of this library, not the git variant.

**Comment by mykolamor** [comment]
Update: works for `godot = { git = "https://github.com/godot-rust/gdext.git", version = "0.3.5", features = ["experimental-threads"] }`, thanks @heckmarr 
I don't know what broke and where, but I encourage to update the docs or figure out what's wrong so others don't run into the same issue.

**Comment by Bromeon** [comment]
> [@Bromeon](https://github.com/Bromeon) one thing that I noticed while tinkering (which doesn't apply to this issue) is that godot falls back to an older Sdk build tools version if the target one is not installed, but since we manually specify the clang version, that would be the wrong one. Is it possible to update the documentation to force users to double-check the warning: `Could not find version of build tools that matches Target SDK, using <older version>`?

If you have the time, could you open a pull request in https://github.com/godot-rust/book?

> Update: works for `godot = { git = "https://github.com/godot-rust/gdext.git", version = "0.3.5", features = ["experimental-threads"] }`, thanks [@heckmarr](https://github.com/heckmarr)

Does it work without `git = ...` and just `version = "0.3.5"`? Because Git is a moving target and not reproducible.

**Comment by mykolamor** [comment]
@Bromeon I tried removing the git url, only leaving the version and the features. Cleaned the rust cache, recompiled from scratch. Seems to work. Unless some Godot cache still kept some working object files or smth, I don't see anything else wrong with it.

**Comment by ansdor** [comment]
sorry I haven't been active on this issue, I had to take care of some personal stuff this past month

has this been solved? I tried to compile my game for android using my container from #1250 and it doesn't work anymore with version 0.4. the rust part compiles fine, but when I try to export it from godot I get this:

```
[   0% ] first_scan_filesystem | Started Project initialization (5 steps)
[   0% ] first_scan_filesystem | Scanning file structure...
[  16% ] first_scan_filesystem | Loading global class names...
[  33% ] first_scan_filesystem | Verifying GDExtensions...
ERROR: Condition "!FileAccess::exists(path)" is true. Returning: ERR_FILE_NOT_FOUND
   at: open_dynamic_library (drivers/unix/os_unix.cpp:1057)
ERROR: GDExtension dynamic library not found: 'res://sushi.gdextension'.
```

the .gdextension file is written as recommended by the godot-rs book:
```
[configuration]
entry_symbol = "gdext_rust_init"
compatibility_minimum = 4.4
reloadable = true

[libraries]
linux.debug.x86_64 = "res://../rust/target/debug/libsushi.so"
linux.release.x86_64 = "res://../rust/target/release/libsushi.so"
windows.debug.x86_64 = "res://../rust/target/debug/sushi.dll"
windows.release.x86_64 = "res://../rust/target/release/sushi.dll"
macos.debug = "res://../rust/target/debug/libsushi.dylib"
macos.release = "res://../rust/target/release/libsushi.dylib"
macos.debug.arm64 = "res://../rust/target/debug/libsushi.dylib"
macos.release.arm64 = "res://../rust/target/release/libsushi.dylib"
web.debug.wasm32 = "res://../rust/target/wasm32-unknown-emscripten/debug/sushi.wasm"
web.release.wasm32 = "res://../rust/target/wasm32-unknown-emscripten/release/sushi.wasm"
android.debug.arm64 = "res://../rust/target/aarch64-linux-android/debug/libsushi.so"
android.release.arm64 = "res://../rust/target/aarch64-linux-android/release/libsushi.so"
```

and the path is valid:
```
[root@a230a8becb31 godot]# pwd
/proj/sushi-night-fever/godot
[root@a230a8becb31 godot]# ls ../rust/target/aarch64-linux-android/debug/libsushi.so
../rust/target/aarch64-linux-android/debug/libsushi.so
```

**Comment by cherish-ltt** [comment]
godot-engine: v4.4.1
godot-crate: v0.3.5 -> v0.4.2
When I switched from `v0.3.5` to `v0.4.2`, I also made the same error.But it's in Windows
```
35:32.983 23600 23639 E godot   : ERROR: Cannot get class 'Demo'.
09-08 16:35:32.983 23600 23639 E godot   : WARNING: Node Demo of type Demo cannot be created. A placeholder will be created instead.
```

**Comment by Yarwin** [comment]
> godot-engine: v4.4.1
> godot-crate: v0.3.5 -> v0.4.2
> When I switched from `v0.3.5` to `v0.4.2`, I also made the same error.But it's in Windows

in the terminal/console (not editor output!) you should get a proper warning. 

Godot-rust by default uses latest prebuilt – which can only run with newer runtime version (i.e. API 4.4 + editor 4.5 => good. Api 4.5 + editor 4.4 => bad). You need to specify what prebuilt version you want to use via feature – see: https://godot-rust.github.io/book/toolchain/godot-version.html. 

(the output in question is present only in the console/terminal because we can't print to editor if we can't open the library because it was compiled against newer Godot version)

**Comment by cherish-ltt** [comment]
> > godot-engine: v4.4.1
> > godot-crate: v0.3.5 -> v0.4.2
> > When I switched from `v0.3.5` to `v0.4.2`, I also made the same error.But it's in Windows
> 
> in the terminal/console (not editor output!) you should get a proper warning.
> 
> Godot-rust by default uses latest prebuilt – which can only run with newer runtime version (i.e. API 4.4 + editor 4.5 => good. Api 4.5 + editor 4.4 => bad). You need to specify what prebuilt version you want to use via feature – see: https://godot-rust.github.io/book/toolchain/godot-version.html.
> 
> (the output in question is present only in the console/terminal because we can't print to editor if we can't open the library because it was compiled against newer Godot version)

Thank you, using godot rust v0.4.2, I see that i can switch to api4.4 using features. Is that correct?

**Comment by Yarwin** [comment]
> Thank you, using godot rust v0.4.2, I see that i can switch to api4.4 using features. Is that correct?

yes

**Comment by Bromeon** [comment]
I'll close this. Note that there's also newer Android issue: #1423.
